version: "3.9"
   
services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
      args:
        TZ: ${TZ}
    volumes:
      - .:/code:delegated
      # use the container's node_modules folder (don't override)
      - /code/frontend/node_modules/
      - /code/static/
      - ${HOME}/mylasecrets:/secrets
    ports:
      - "5000:5000"
      - "3000:3000"
    container_name: canvas_app_explorer
